version: '2'

services:
  MySQL:
    image: mysql:5.7
    container_name: MySQL
    volumes:
      - ./MySQL/init:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=userdb"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
    networks:
      localnet:
        ipv4_address: 192.168.20.2
  
  SiloServer:
    image: microsoft/aspnetcore:3.1
    container_name: SiloServer
    volumes:
      - ./:/app
    command: /bin/bash -c 'cd /app/ && dotnet run bin/Debug/netcoreapp3.1/SiloServer.dll'
    ports:
      - "11111:11111"
    networks:
      localnet:
        ipv4_address: 192.168.20.3

  BlackListChecker:
    image: microsoft/aspnetcore:3.1
    container_name: BlackListChecker
    volumes:
      - ./:/app
    command: /bin/bash -c 'cd /app/ && dotnet run bin/Debug/netcoreapp3.1/BlackListChecker.dll'
    depends_on: 
      - MySQL
    networks:
      localnet:
        ipv4_address: 192.168.20.4

  UserServer01:
    image: microsoft/aspnetcore:3.1
    container_name: UserService01
    volumes:
      - ./:/app
    command: /bin/bash -c 'cd /app/ && dotnet run bin/Debug/netcoreapp3.1/UserService.dll'
    depends_on: 
      - MySQL
      - SiloServer
    environment:
      - "ASPNETCORE_URLS=http://0.0.0.0:5001"
    ports:
      - "5001:5001"
    networks:
      localnet:
        ipv4_address: 192.168.20.5

  UserServer02:
    image: microsoft/aspnetcore:3.1
    container_name: UserService02
    volumes: 
      - ./:/app
    command: /bin/bash -c 'cd /app/ && dotnet run bin/Debug/netcoreapp3.1/UserService.dll'
    depends_on: 
      - MySQL
      - SiloServer
    environment:
      - "ASPNETCORE_URLS=http://0.0.0.0:5001"
    ports:
      - "5002:5001"
    networks:
      localnet:
        ipv4_address: 192.168.20.6


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.20.0/16
