version: '2'

services:
  mysql:
    image: mysql:5.6
    container_name: MySQL
    volumes:
      - ./MySQL/init:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=userdb"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
    networks:
      localnet:
        ipv4_address: 192.168.20.2
  
  siloserver:
    build: ./SiloServer 
    container_name: SiloServer
    ports:
      - "11111:11111"
    networks:
      localnet:
        ipv4_address: 192.168.20.3

  blacklistchecker:
    build: ./BlackListChecker
    container_name: BlackListChecker
    depends_on: 
      - mysql
    networks:
      localnet:
        ipv4_address: 192.168.20.4

  userserver01:
    build: ./UserService
    container_name: UserService01
    depends_on: 
      - mysql
      - siloserver
    ports:
      - "5001:5001"
    networks:
      localnet:
        ipv4_address: 192.168.20.5

  userserver02:
    build: ./UserService
    container_name: UserService02
    depends_on: 
      - mysql
      - siloserver
    ports:
      - "5002:5001"
    networks:
      localnet:
        ipv4_address: 192.168.20.6


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.20.0/16
